name: "Flutter Analyze Commenter"

description: "Auto comment on PRs based on Flutter Analyze results"

author: "yorifuji"

branding:
  icon: code
  color: blue

inputs:
  analyze-log:
    description: "Path to the log file by flutter analyze command"
    required: false
  custom-lint-log:
    description: "(Optional)Path to the log file by dart run custom_lint command"
    required: false
  verbose:
    description: "Enable verbose logging"
    required: false
    default: false
  max_issues:
    description: "Maximum number of issues to comment on"
    required: false
    default: 10

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      if: ${{ github.event_name == 'pull_request' }}
      env:
        ANALYZE_LOG: ${{ inputs.analyze-log }}
        ANALYZE_LOG_DEPRECATED: ${{ inputs.analyze_log }}
        CUSTOM_LINT_LOG: ${{ inputs.custom-lint-log }}
        VERBOSE: ${{ inputs.verbose }}
      with:
        retries: 3
        script: |
          const analyzeLog = process.env.ANALYZE_LOG || process.env.ANALYZE_LOG_DEPRECATED;
          const customLintLog = process.env.CUSTOM_LINT_LOG;
          const verboseLogging = process.env.VERBOSE === 'true';
          const maxIssues = process.env.MAX_ISSUES;

          const workingDir = process.env.GITHUB_WORKSPACE;
          const actionPath = process.env.GITHUB_ACTION_PATH;

          const path = require('path');
          const script = require(path.join(actionPath, 'index.js'));
          await script({ core, github, context, workingDir, analyzeLog, customLintLog, verboseLogging })
      - continue-on-error: true
